### PR TITLE
Add Oxford Dictionary service

### PR DESCRIPTION
**Pull request by myrgy**
this service provider to download sounds from http://www.oxforddictionaries.com

### CODE REVIEW

**Comment by corpulentcoffee** [comment]
The OED will be a great addition to AwesomeTTS. Thanks for putting this together! :+1:

I'm going to grab your branch and will integrate it into the next release.

**Comment by myrgy** [comment]
It has some bug, I'll try to fix it asap.

**Comment by corpulentcoffee** [comment]
What bug are you seeing?

I already fixed some things: accented characters ("mañana" now) and also multi-word input ("United Kingdom" will work now).

Cheers!

**Comment by myrgy** [comment]
(y)
sometimes I've received errors with sounds downloading

**Comment by corpulentcoffee** [comment]
Thank you! Researching how to get MP3s out of the services is a lot of work, so I appreciate the contribution a lot... and now people using AwesomeTTS for English pronunciation will have another good service option. :+1:

**Pull request merged**
